swipe:
    3:
        left:
            shortcut: 'alt+shift+Tab'
        right:
            shortcut: 'alt+Tab'
        up:
            shortcut: 'super'
        down:
            shortcut: 'super'
    4:
        down:
            shortcut: 'alt+F4'
        up:
            shortcut: 'super+F9'
interval:
    swipe: 1
    pinch: 1

threshold:
    swipe: 0.3
    pinch: 0.3
